### PR TITLE
📚 Add TypeScript definitions

### LINKED ISSUE #24: TypeScript types
Hey, this package does exactly what I need!
I'm using TypeScript, and although I can import JS directly, I'd like to have proper types for IntelliSense and stuff.

I'm happy to write the types myself. Would you be willing to integrate them into the repo? It's just an `index.d.ts` file in the root folder.
There're two alternatives: a file in the repo or a separate package `@types/tree-crawl` with that file if you don't want to officially support it.

### PR DESCRIPTION
**Pull request by deltaidea**
Closes #24.

image

### CODE REVIEW

**Comment by deltaidea** [comment]
Want me to change anything? Nitpicks are welcome! 😄

**Comment by ngryman** [comment]
Unfortunately I'm not really familiar with Typescript so I trust you on this :) I also took the liberty to add you to the project, si if the API evolves you can easily maintain the types.

Tanks!

**Comment by deltaidea** [comment]
👍 Thank you! Glad I could help.
Could you also bump the version and publish to npm once you have some time?

**Comment by ngryman** [comment]
Done, sorry for the delay.

**Pull request merged**
