### PR TITLE
Added types property to package.json

### PR DESCRIPTION
**Pull request by jameswlane**
This allows TypeScript to recognize the the index.d.ts

### CODE REVIEW

**Comment by ngryman** [comment]
Thanks @jameswlane, it's better when the file is actually here indeed 😂

**Comment by ngryman** [comment]
...and published as `1.0.5`

**Comment by tehwalris** [comment]
@ngryman Hey, I can't find `1.0.5` on npm 😅

**Comment by ngryman** [comment]
Oops I had an error while publishing, should be ok now.

**Pull request merged**
